// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxiUPI8T_9abG8olQox2MnivrigL8yUQ',
    appId: '1:499840188255:web:f61be5fcb6937b6a6240ea',
    messagingSenderId: '499840188255',
    projectId: 'fastrends-d3b73',
    authDomain: 'fastrends-d3b73.firebaseapp.com',
    storageBucket: 'fastrends-d3b73.appspot.com',
    measurementId: 'G-9174DZRZ98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwFBjPo6Oe4XsqULL_bA7JhCF2NQCJM4',
    appId: '1:499840188255:android:9774bf5c3364c3ca6240ea',
    messagingSenderId: '499840188255',
    projectId: 'fastrends-d3b73',
    storageBucket: 'fastrends-d3b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdZtglhKYdKR2YTU9fLqJ34moIp1ZDdbc',
    appId: '1:499840188255:ios:d11dab19da775bfd6240ea',
    messagingSenderId: '499840188255',
    projectId: 'fastrends-d3b73',
    storageBucket: 'fastrends-d3b73.appspot.com',
    iosBundleId: 'com.example.fastrends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdZtglhKYdKR2YTU9fLqJ34moIp1ZDdbc',
    appId: '1:499840188255:ios:d11dab19da775bfd6240ea',
    messagingSenderId: '499840188255',
    projectId: 'fastrends-d3b73',
    storageBucket: 'fastrends-d3b73.appspot.com',
    iosBundleId: 'com.example.fastrends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoxiUPI8T_9abG8olQox2MnivrigL8yUQ',
    appId: '1:499840188255:web:ae4ed2fbed7072636240ea',
    messagingSenderId: '499840188255',
    projectId: 'fastrends-d3b73',
    authDomain: 'fastrends-d3b73.firebaseapp.com',
    storageBucket: 'fastrends-d3b73.appspot.com',
    measurementId: 'G-37SXWY3902',
  );
}
